//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Log
    {
        public System.Guid Activity_Log_ID { get; set; }
        public System.DateTime Activity_Log_Date { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Page { get; set; }
        public string Action { get; set; }
        public string Message { get; set; }
    }
}
