//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canopy
    {
        public Canopy()
        {
            this.Bids = new HashSet<Bid>();
            this.Measurement_Lists = new HashSet<Measurement_Lists>();
            this.Measurement_Lists1 = new HashSet<Measurement_Lists>();
        }
    
        public int Canopy_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Size_Width_Measure_ID { get; set; }
        public int Size_Height_Measure_ID { get; set; }
        public int Clearance_Height_Measure_ID { get; set; }
        public Nullable<int> Column_Quantity { get; set; }
        public int Column_Type_ID { get; set; }
        public int Column_Size_Measure_ID { get; set; }
        public int Column_Shape_ID { get; set; }
        public int Column_Spacing_Length_ID { get; set; }
        public Nullable<int> Column_Spacing_Width_ID { get; set; }
        public string Column_Spacing_Notes { get; set; }
        public int Deck_Style_ID { get; set; }
        public Nullable<int> Deck_Color_ID { get; set; }
        public int Deck_Thickness_Measure_ID { get; set; }
        public int Image_ID { get; set; }
        public int Fascia_Height_Measure_ID { get; set; }
        public int Fascia_Type_ID { get; set; }
        public int Fascia_Color_ID { get; set; }
        public int Drainage_Type_ID { get; set; }
        public string Other_Notes { get; set; }
        public string Inclusion_Notes { get; set; }
        public string Exclusion_Notes { get; set; }
        public string General_Inclusion_Notes { get; set; }
        public string General_Exclusion_Notes { get; set; }
        public Nullable<decimal> Base_Price { get; set; }
        public Nullable<decimal> Material_Price { get; set; }
        public Nullable<decimal> Labor_Price { get; set; }
        public Nullable<decimal> Freight_Price { get; set; }
        public Nullable<decimal> Tax_Price { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<decimal> Alt_Base_Price { get; set; }
        public Nullable<int> Design_Loads_Live_Psf { get; set; }
        public Nullable<int> Design_Load_Wind_Mph { get; set; }
        public Nullable<int> Design_Load_Wind_Psf { get; set; }
        public string Design_Load_Notes { get; set; }
        public string Drawing_Sealed { get; set; }
        public string Drawing_State { get; set; }
        public string Drawing_Code { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modifed_Date { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Color Color1 { get; set; }
        public virtual Column_Shapes Column_Shapes { get; set; }
        public virtual Column_Types Column_Types { get; set; }
        public virtual Deck_Styles Deck_Styles { get; set; }
        public virtual Drainage_Types Drainage_Types { get; set; }
        public virtual Fascia_Types Fascia_Types { get; set; }
        public virtual Image Image { get; set; }
        public virtual Measurement Measurement { get; set; }
        public virtual Measurement Measurement1 { get; set; }
        public virtual Measurement Measurement2 { get; set; }
        public virtual Measurement Measurement3 { get; set; }
        public virtual Measurement Measurement4 { get; set; }
        public virtual Measurement Measurement5 { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<Measurement_Lists> Measurement_Lists { get; set; }
        public virtual ICollection<Measurement_Lists> Measurement_Lists1 { get; set; }
    }
}
