//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Column_Spacing_Widths
    {
        public int Column_Spacing_Width_ID { get; set; }
        public int Canopy_ID { get; set; }
        public int Measurement_ID { get; set; }
        public int Sequence { get; set; }
    
        public virtual Measurement Measurement { get; set; }
    }
}
