//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Column_Spacing_Lengths
    {
        public System.Guid Column_Spacing_Length_ID { get; set; }
        public System.Guid Canopy_ID { get; set; }
        public System.Guid Measurement_ID { get; set; }
        public int Sequence { get; set; }
    
        public virtual Canopy Canopy { get; set; }
        public virtual Measurement Measurement { get; set; }
    }
}
