//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Info
    {
        public Contact_Info()
        {
            this.Customers = new HashSet<Customer>();
            this.Sales_Persons = new HashSet<Sales_Persons>();
        }
    
        public int Contact_Info_ID { get; set; }
        public int Contact_Type_ID { get; set; }
        public string Contact_Text { get; set; }
        public Nullable<int> Created_By { get; set; }
        public System.DateTime Create_Date { get; set; }
    
        public virtual Contact_Types Contact_Types { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Sales_Persons> Sales_Persons { get; set; }
    }
}
