//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Canopies = new HashSet<Canopy>();
        }
    
        public int Image_ID { get; set; }
        public Nullable<int> Color_ID { get; set; }
        public string Image_Path { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
    
        public virtual ICollection<Canopy> Canopies { get; set; }
    }
}
