//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public Measurement()
        {
            this.Canopies = new HashSet<Canopy>();
            this.Canopies1 = new HashSet<Canopy>();
            this.Canopies2 = new HashSet<Canopy>();
            this.Canopies3 = new HashSet<Canopy>();
            this.Canopies4 = new HashSet<Canopy>();
            this.Canopies5 = new HashSet<Canopy>();
            this.Canopies6 = new HashSet<Canopy>();
            this.Measurement_Lists = new HashSet<Measurement_Lists>();
        }
    
        public int Measurement_ID { get; set; }
        public Nullable<int> Feet { get; set; }
        public Nullable<int> Inches { get; set; }
    
        public virtual ICollection<Canopy> Canopies { get; set; }
        public virtual ICollection<Canopy> Canopies1 { get; set; }
        public virtual ICollection<Canopy> Canopies2 { get; set; }
        public virtual ICollection<Canopy> Canopies3 { get; set; }
        public virtual ICollection<Canopy> Canopies4 { get; set; }
        public virtual ICollection<Canopy> Canopies5 { get; set; }
        public virtual ICollection<Canopy> Canopies6 { get; set; }
        public virtual ICollection<Measurement_Lists> Measurement_Lists { get; set; }
    }
}
