//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Persons
    {
        public Sales_Persons()
        {
            this.Bids = new HashSet<Bid>();
            this.Contact_Info = new HashSet<Contact_Info>();
        }
    
        public int Sales_Person_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
    
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<Contact_Info> Contact_Info { get; set; }
    }
}
