//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaneBids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_Info
    {
        public Shipping_Info()
        {
            this.Bids = new HashSet<Bid>();
            this.Bids1 = new HashSet<Bid>();
            this.Bids2 = new HashSet<Bid>();
        }
    
        public int Shipping_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Address_ID { get; set; }
    
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<Bid> Bids1 { get; set; }
        public virtual ICollection<Bid> Bids2 { get; set; }
    }
}
